# Better readibility
SpaceInsideParens:
  Enabled: false

# Better readibility
SpaceInsideBrackets:
  Enabled: false

# 80 is way too low
LineLength:
  Max: 120

# 10 is too low
MethodLength:
  Max: 15

ClassLength:
  Max: 200
